"""add users interested in unis

Revision ID: 2ff409a42dd2
Revises: 8b53d453f6d0
Create Date: 2022-07-20 17:26:56.082791

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision = '2ff409a42dd2'
down_revision = '8b53d453f6d0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('userunilink',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('uni_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['uni_id'], ['university.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'uni_id')
    )
    op.drop_constraint('education_owner_id_fkey', 'education', type_='foreignkey')
    op.create_foreign_key(None, 'education', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('experience_owner_id_fkey', 'experience', type_='foreignkey')
    op.create_foreign_key(None, 'experience', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('profilephoto_owner_id_fkey', 'profilephoto', type_='foreignkey')
    op.create_foreign_key(None, 'profilephoto', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'profilephoto', type_='foreignkey')
    op.create_foreign_key('profilephoto_owner_id_fkey', 'profilephoto', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'experience', type_='foreignkey')
    op.create_foreign_key('experience_owner_id_fkey', 'experience', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'education', type_='foreignkey')
    op.create_foreign_key('education_owner_id_fkey', 'education', 'user', ['owner_id'], ['id'], ondelete='CASCADE')
    op.drop_table('userunilink')
    # ### end Alembic commands ###
